### ISSUE TITLE
Getting error while reading .vol file

### ISSUE THREAD

**Issue by Naveedkhan283** [MedVisBonn/eyepy#1]
* eyepy version: 0.3.6
* Python version: 3.7.1
* Operating System: windows 10

### Description

I am trying to read meta data information from .vol file but it gives error "buffer is too small for requested array"
I have also attached the screen shot of the error.

Could please help why i am getting this error ?

Thanks,
Naveed

![error reading vol](https://user-images.githubusercontent.com/11353538/144845840-2e070a25-f08b-42e4-babf-bf049092b740.jpg)

**Comment by Oli4** [comment]
Dear Naveed, 

Sorry for the late reply. I never encountered this issues so far. Where did you get this data from?  I just released eyepy 0.4, give it a try. 

```python
import eyepy as ep
ev = ep.import_heyex_vol(path)
```

If it is still not working let me know
Best regards
Olivier
