### ISSUE TITLE
Installation problems on Google Colab

### ISSUE THREAD

**Issue by drombas** [MedVisBonn/eyepy#10]
* eyepy version: 0.4.0
* Python version: 3.8.10
* Operating System: Linux-5.10.147+-x86_64-with-glibc2.29

### Description
Hi! I tried installing eyepy in a fresh Google Colab notebook but I got some dependency error.
Not sure if it is related to Google Colab or eyepy but it may be similar to #8 .
I think I tested the same thing with the previous eyepy version and it worked fine.
![image](https://user-images.githubusercontent.com/50577357/220595088-ab2b7977-0c27-4df7-b401-00895a574b2c.png)

Here is the [link](https://colab.research.google.com/drive/1xAKb1mzwTTlhQTlv0AGdwzfiSSQZPBBi?usp=sharing) to the notebook.

**Comment by Oli4** [comment]
Hey @drombas 

There seems to be numba installed in your Colab environment which requires a numpy version < 1.24.0. This is in conflict with the current dependency of eyepy on numpy. For now you could uninstall numba if this is possible, but I am going to set the numpy requirement to a wider version range for the next release, this restriction was unintentional. This should fix the issue. Next release is probably done this week.

**Comment by Oli4** [comment]
Should work with version v0.8.1. Thank you for letting me know about this issue :)
