### ISSUE TITLE
Is center of the grid (e.g. ETDRS) defined anywhere in the HEYEX .vol file?

### ISSUE THREAD

**Issue by charsooghi** [MedVisBonn/eyepy#17]
* eyepy version: 0.12.2
* Python version: 3.11.5
* Operating System: Windows 11

### Description

Thank you for the great library, it helps a lot, it is amazing. 
I am loding OCT Raw Data (HEYEX .vol format). I am wondering if the center of the grid (e.g. ETDRS grid) is written somewhere in the .vol file.

I noticed that there is an optional `center` argument in `annotations.py`
```Phython
center: Optional[tuple[float, float]] = None,
```

Also in `grids.py` it is written that `if center is not None` there is a transformation and if it is None probably just it will take the center of the localizer image. 

```Python
if center is not None:
        translation = transform.AffineTransform(translation=np.array(center) -
                                                np.array(mask_shape) / 2)
```

I am wondering if there is such an information in HEYEX .vol file or it is always use the center of the localizer image unless we pass a tuple ourselves. 

Thank you

**Comment by Oli4** [comment]
Dear @charsooghi, 

you are correct by default eyepy uses the center of the image for the ETDRS grid. You can provide another center to shift the grid for example if you have manual annotations of the fovea. eyepy does not extract the center from the VOL files. As far as I know the fovea position is not stored in the VOL files but most VOL data I am working with is centered on the fovea.

**Comment by charsooghi** [comment]
Dear @Oli4 
Thank you for quick response and the clarification. You are right, meanwhile I looked in detial to HEYEX to see if there is any trace of fovea coordinates, but I couldn't find any. As I understood fovea detection is not strightforwad and is not implemented by default.

Thank you again, it helped a lot. :-)

**Comment by Oli4** [comment]
You are welcome :)
