### ISSUE TITLE
Opening Heyex .edb .pdb .sdb files

### ISSUE THREAD

**Issue by paulschmeida** [MedVisBonn/eyepy#18]
We are looking to run some analysis on over 35k files from Heyex. These files are structured in folders per patient and it seems that the actual imaging is in .sdb files. Any idea how to open these files programmatically in Python? Seems like every project out there expects a different file format...

**Comment by Oli4** [comment]
Dear @paulschmeida, 

I believe that the edb pdb and sdb are internal files of the Heyex Database. There is probably some way to read them but I have never tried. I would recommend to use the RAW export to VOL and then you can use eyepy to read and visualize the volumes.
