### ISSUE TITLE
Disable motion correction

### ISSUE THREAD

**Issue by yiqian-wang** [MedVisBonn/eyepy#3]
Hi, I wonder if there is a way to load the bscans & layer segmentation data without performing motion correction via affine transformation?

**Comment by Oli4** [comment]
Hey yiqian-wang, 

eyepy does not perform any motion correction. The transform which can be given to the EyeVolume object maps a 2D projection of the volume data into the enface space, for annotation overlays for example. As of my understanding data exported with HEYEX in the .xml or .vol format is already motion corrected.

**Comment by yiqian-wang** [comment]
I see, thanks for your reply!
