### ISSUE TITLE
[Bug] Bscans and segmentation displayed incorrectly

### ISSUE THREAD

**Issue by drombas** [MedVisBonn/eyepy#7]
* eyepy version: 0.7.0
* Python version: 3.8.10
* Operating System: Linux-5.10.147+-x86_64-with-glibc2.29

### Description
Hi there. I am testing the package a bit to get an idea of how it works.
When plotting B-scans with segmentation overlay the boundaries do not match. 
It seems that what happens is that segmentation and B-scans are stored with different orders.

### What I Did
![image](https://user-images.githubusercontent.com/50577357/218435637-b607e857-c0d9-4c40-be00-b7e1d45e9117.png)

**Comment by Oli4** [comment]
Thank you very much for reporting this. You did everything right. For v0.7.0 I changed some internal indexing which is not reflected in the plotting yet. There is going to be a new version with several fixes including this one in about one hour :)

**Comment by Oli4** [comment]
I just created a new release. I think it should work now as expected. Otherwise, let me know.

**Comment by drombas** [comment]
Brilliant, it works now! I will play with it for a while and let you know any suggestions/questions.
